### ISSUE TITLE
"getOutputObjectFromInput" is not defined

### ISSUE THREAD

**Issue by mplewis** [b00giZm/express-ifttt-webhook#1]
Hey! I love the project so far. I'm not able to use `getOutputObjectFromInput` as I'm not sure where to find it. How can I use `getOutputObjectFromInput` to transform a JSON object?

Stacktrace:

```
ReferenceError: getOutputObjectFromInput is not defined
    at /app/server.js:10:13
    at /app/node_modules/express-ifttt-webhook/node_modules/async/lib/async.js:125:13
    at /app/node_modules/express-ifttt-webhook/node_modules/async/lib/async.js:656:23
    at /app/node_modules/express-ifttt-webhook/node_modules/async/lib/async.js:570:21
    at /app/node_modules/express-ifttt-webhook/node_modules/async/lib/async.js:249:17
    at async.each (/app/node_modules/express-ifttt-webhook/node_modules/async/lib/async.js:124:9)
    at _asyncMap (/app/node_modules/express-ifttt-webhook/node_modules/async/lib/async.js:248:13)
    at _each (/app/node_modules/express-ifttt-webhook/node_modules/async/lib/async.js:46:24)
    at Array.forEach (native)
    at Object.map (/app/node_modules/express-ifttt-webhook/node_modules/async/lib/async.js:219:23)
```

**Comment by b00gizm** [comment]
Hi Matthew,

sorry for the confusion. `getOutputObjectFromInput` is no actual method, but only pseudo code meaning "do your own stuff to transform the values as you need" ;) I'll fix that in the documentation

Anyway, thanks for the feedback :+1:
